[profile.default]
libs = ["lib"]
out = "out"
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
src = "src"

# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = {key = "${ETHERSCAN_API_KEY}"}

# [rpc_endpoints]
# sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
depth = 128
fail_on_revert = true
runs = 128

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
